---
- name: Set up Docker and Nginx container
  hosts: aws_servers
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Explicitly set Python interpreter for Ubuntu
  tasks:
    # Ensure Python pip is installed
    - name: Ensure Python pip is installed
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    # Install specific versions of requests and urllib3
    - name: Install specific versions of requests and urllib3
      pip:
        name:
          - requests==2.28.1   # Compatible with older urllib3
          - urllib3==1.26.5    # Compatible with OpenSSL 1.0.2k
        state: present
        extra_args: --ignore-installed
        executable: /usr/bin/pip3

    # Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    # Start Docker service
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    # Add user to docker group
    - name: Add user to docker group
      user:
        name: ubuntu  # Use 'ec2-user' for Amazon Linux or 'ubuntu' for Ubuntu-based systems
        groups: docker
        append: yes

    # Pull Nginx Docker image
    - name: Pull Nginx Docker image
      community.docker.docker_image:
        name: nginx
        source: pull

    # Run Nginx container
    - name: Run Nginx container
      community.docker.docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
